#!/usr/bin/env python3
"""
Sync Sub-Agent Personas Script

Synchronizes sub-agent persona Markdown files from the Single Source of Truth (.agents/agents/)
to platform-native directories:
  - Claude Code: .claude/agents/<name>.md & .claude/subagents/<name>.md (YAML frontmatter)
  - OpenAI Codex: .codex/agents/<name>.toml & .codex/subagents/<name>.toml (TOML schema)

Usage:
  python3 scripts/sync_subagents.py
"""

import sys
from pathlib import Path
import re

HEADER_COMMENT_MD = "<!-- DO NOT EDIT DIRECTLY: GENERATED BY scripts/sync_subagents.py -->\n\n"
HEADER_COMMENT_TOML = "# DO NOT EDIT DIRECTLY: GENERATED BY scripts/sync_subagents.py\n\n"

REQUIRED_AGY_FIELDS = [
    "name",
    "description",
    "enable_write_tools",
    "enable_mcp_tools",
    "enable_subagent_tools",
    "tools",
    "skills",
]


def parse_frontmatter(content: str):
    """
    Extracts YAML frontmatter text and Markdown body from a file content.
    Returns (frontmatter_text, body_text).
    """
    if not content.startswith("---"):
        return None, content

    parts = content.split("---", 2)
    if len(parts) < 3:
        return None, content

    frontmatter_text = parts[1].strip()
    body_text = parts[2].lstrip()
    return frontmatter_text, body_text


def extract_field(frontmatter_text: str, field_name: str) -> str:
    """
    Extracts a string field value from simple YAML frontmatter.
    """
    match = re.search(rf'^{field_name}\s*:\s*"(.*?)"', frontmatter_text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    match = re.search(rf'^{field_name}\s*:\s*(.*)', frontmatter_text, re.MULTILINE)
    if match:
        return match.group(1).strip(' "\'')
    return ""


def validate_frontmatter_fields(frontmatter_text: str) -> list:
    """
    Validates presence of required fields in YAML frontmatter string.
    Returns list of missing fields.
    """
    missing = []
    for field in REQUIRED_AGY_FIELDS:
        pattern = rf"^{field}\s*:"
        if not re.search(pattern, frontmatter_text, re.MULTILINE):
            missing.append(field)
    return missing


def build_claude_content(frontmatter_text: str, body_text: str) -> str:
    """
    Formats persona file for Claude Code (.claude/agents/<name>.md & .claude/subagents/<name>.md).
    Preserves YAML frontmatter and appends DO NOT EDIT header.
    """
    return f"{HEADER_COMMENT_MD}---\n{frontmatter_text}\n---\n\n{body_text}"


def build_codex_toml(name: str, description: str, body_text: str) -> str:
    """
    Formats persona file for OpenAI Codex (.codex/agents/<name>.toml & .codex/subagents/<name>.toml).
    Outputs valid TOML configuration format.
    """
    escaped_body = body_text.replace('"""', r'\"\"\"')
    return (
        f"{HEADER_COMMENT_TOML}"
        f'name = "{name}"\n'
        f'description = "{description}"\n\n'
        f'developer_instructions = """\n{escaped_body}"""\n'
    )


def main():
    repo_root = Path(__file__).resolve().parent.parent
    source_dir = repo_root / ".agents" / "agents"

    claude_agents_dir = repo_root / ".claude" / "agents"
    claude_subagents_dir = repo_root / ".claude" / "subagents"

    codex_agents_dir = repo_root / ".codex" / "agents"
    codex_subagents_dir = repo_root / ".codex" / "subagents"

    if not source_dir.exists():
        print(f"Error: Source directory {source_dir} does not exist.", file=sys.stderr)
        sys.exit(1)

    source_files = sorted(source_dir.glob("*.md"))
    if not source_files:
        print(f"Warning: No sub-agent .md files found in {source_dir}.")
        sys.exit(0)

    claude_agents_dir.mkdir(parents=True, exist_ok=True)
    claude_subagents_dir.mkdir(parents=True, exist_ok=True)
    codex_agents_dir.mkdir(parents=True, exist_ok=True)
    codex_subagents_dir.mkdir(parents=True, exist_ok=True)

    print(f"Found {len(source_files)} sub-agent persona(s) in {source_dir.relative_to(repo_root)}:\n")

    errors = []
    synced_count = 0

    # Clean up obsolete .md files in .codex/subagents/ if present
    for old_md in codex_subagents_dir.glob("*.md"):
        old_md.unlink()

    for src_file in source_files:
        content = src_file.read_text(encoding="utf-8")
        fm_text, body_text = parse_frontmatter(content)

        if fm_text is None:
            errors.append(f"[{src_file.name}] Missing YAML frontmatter ('---').")
            continue

        missing = validate_frontmatter_fields(fm_text)
        if missing:
            errors.append(f"[{src_file.name}] Missing required YAML frontmatter fields: {', '.join(missing)}")
            continue

        name = extract_field(fm_text, "name") or src_file.stem
        description = extract_field(fm_text, "description")

        # Generate target contents
        claude_content = build_claude_content(fm_text, body_text)
        codex_toml = build_codex_toml(name, description, body_text)

        # Write Claude targets (.claude/agents/<name>.md & .claude/subagents/<name>.md)
        (claude_agents_dir / src_file.name).write_text(claude_content, encoding="utf-8")
        (claude_subagents_dir / src_file.name).write_text(claude_content, encoding="utf-8")

        # Write Codex targets (.codex/agents/<name>.toml & .codex/subagents/<name>.toml)
        toml_name = f"{src_file.stem}.toml"
        (codex_agents_dir / toml_name).write_text(codex_toml, encoding="utf-8")
        (codex_subagents_dir / toml_name).write_text(codex_toml, encoding="utf-8")

        print(f"  ✓ {src_file.name} -> .claude/agents/ & .codex/agents/")
        synced_count += 1

    print()
    if errors:
        print("Validation / Sync Errors:")
        for err in errors:
            print(f"  ✗ {err}")
        sys.exit(1)

    print(f"Successfully synced {synced_count} sub-agent persona(s) across platforms.")


if __name__ == "__main__":
    main()
